stages:
  - prepare
  - build
  - publish

variables:
  b2cClientId: "$Secret_B2cClientId"
  b2cResirectUrl: "rorub2c://com.eleks.YourTest"
  b2cAuthority: "https://login.microsoftonline.com/tfp/rorub2c.onmicrosoft.com/B2C_1_Mail-Signup"
  b2cScopes: "https://rorub2c.onmicrosoft.com/yourtest/read"
  
  restEndpoint: "https://roru-yt.azurewebsites.net"

  ac_group: "Collaborators"
  ac_owner: "ELEKS-R-D"
  # ac_app_prefix: "YourTest"
  ac_app_prefix: "ci-test"
  ac_app: "$ac_owner/$ac_app_prefix-$ac_app_sufix"
  ac_token: $APPCENTER_TOKEN

before_script:
    - export Secret_B2cClientId="$b2cClientId"
    - export Secret_B2cRedirectUri="$b2cResirectUrl"
    - export Secret_B2cAuthority="$b2cAuthority"
    - export Secret_B2cScopes="$b2cScopes"
    
    - export Secret_RestEndpoint="$restEndpoint"

.mobile_before_script: &mobile_before_script
  before_script:
    - cd src/Mobile/YourTest
  script:
    - ""

restore:mobile:
  <<: *mobile_before_script
  stage: prepare
  tags:
    - xamarin
  script:
    - nuget restore

build:mobile:droid:
  <<: *mobile_before_script
  stage: build
  dependencies:
    - build:mobile
  tags:
    - xamarin
  script:
    - "msbuild YourTest.Android/YourTest.Android.csproj /p:Configuration=Release /t:SignAndroidPackage"
    - yes | cp YourTest.Android/bin/Release/com.eleks.YourTest-Signed.apk com.eleks.YourTest-Signed.apk
  artifacts:
    paths:
      - "com.eleks.YourTest-Signed.apk"

build:mobile:ios:
  <<: *mobile_before_script
  stage: build
  dependencies:
    - build:mobile
  tags:
    - xamarin
  script:
    - "msbuild YourTest.iOS/YourTest.iOS.csproj /p:Configuration=Release /t:Rebuild" 

publish:appcenter:droid:
  variables:
    ac_app_sufix: "Droid"
  stage: publish
  dependencies:
    - build:mobile:droid
  tags:
    - appcenter
  script:
    - "appcenter distribute release -f com.eleks.YourTest-Signed.apk -g $ac_group -a $ac_app --token ac_token"